# Generated by Django 4.1.7 on 2025-12-20 16:41

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
