# Generated by Django 4.1.7 on 2026-08-05 00:41

import django.core.validators
from django.db import migrations, models
from django.utils.text import slugify


def deduplicate_course_slugs(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    used_slugs = set()

    for course in Course.objects.order_by("id"):
        base_slug = slugify(course.slug or course.name) or f"course-{course.id}"
        candidate = base_slug
        suffix = 2

        while candidate in used_slugs:
            candidate = f"{base_slug}-{suffix}"
            suffix += 1

        if course.slug != candidate:
            course.slug = candidate
            course.save(update_fields=["slug"])

        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.RunPython(deduplicate_course_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='course_price_gte_zero'),
        ),
    ]
